<script setup>
import { computed, watch } from "vue"
import { tab, DIFF_TABS } from "../composables/useTab.js"
import { useCompare } from "../composables/useCompare.js"
import { useCompareDiff } from "../composables/useCompareDiff.js"

// features are generated by the viewer rather than read out of the jar, so a
// version comparison has nothing to compare them against and trades the tab for
// the three diff lists
const compare = useCompare()
const diff = useCompareDiff()
const comparing = computed(() => compare.versionArmed())
const count = id => (void diff.state.rev, diff.state.counts[id])

// no tabs until the sweep lands, then only the lists with something in them
const shown = computed(() => {
  void diff.state.rev
  return diff.state.ready ? DIFF_TABS.filter(([id]) => count(id)) : []
})

watch(comparing, on => { tab.value = on ? "changed" : "structures" })
watch(shown, list => {
  if (list.length && !list.some(([id]) => id === tab.value)) tab.value = list[0][0]
})
</script>

<template>
  <nav class="tabs" v-if="!comparing || shown.length">
    <template v-if="comparing">
      <button v-for="[id, label] in shown" :key="id" :class="{ active: tab === id }" @click="tab = id">
        {{ label }}<span class="n">{{ count(id) }}</span>
      </button>
    </template>
    <template v-else>
      <button :class="{ active: tab === 'structures' }" @click="tab = 'structures'">Structures</button>
      <button :class="{ active: tab === 'features' }" @click="tab = 'features'">Features</button>
    </template>
  </nav>
</template>

<style scoped>
/* the negative margin cancels the section gap so the buttons sit flush on the tree border */
.tabs {
  display: flex;
  gap: 4px;
  margin-bottom: -8px;
}

.tabs button {
  flex: 1;
  padding: 5px 0;
  font-size: 12px;
  background: var(--bg);
  border: 1px solid var(--border);
  border-radius: 6px 6px 0 0;
  border-bottom: none;
  color: var(--text-dim);
  cursor: pointer;
}

.tabs button.active {
  color: var(--text);
  background: #ffffff10;
}

.tabs .n {
  margin-left: 4px;
  font-variant-numeric: tabular-nums;
  opacity: 0.7;
}
</style>
